### PR TITLE
improved functionality on profile, goals and tasks

### PR DESCRIPTION
**Pull request by aruvham**

### CODE REVIEW

**Review by huawillian — COMMENTED** [review]
Uhh it seems bowerrc and readme was changed

**Review by huawillian — CHANGES_REQUESTED** [review]
Make another commit and put the bower rc and read me back to upstream devs. I think git is still behaving strangely.

**Comment by aruvham** [comment]
it is, I don't remember doing those changes

**Comment by huawillian** [comment]
Well... let me just merge this then.
We'll go back and change the 2 files later:
bowerrc
README

**Pull request merged**
